" Use unix line endings
set ff=unix

" Set syntax highlighting based on colormode state file (~/.local/state/colormode)
syntax enable
let s:colormode_file = expand('~/.local/state/colormode')
if filereadable(s:colormode_file) && trim(readfile(s:colormode_file)[0]) ==# 'light'
  set background=light
else
  set background=dark
endif
colorscheme solarized

" Enable autoindentation
set autoindent

" Turn on line numbers
set nu

" Set column for 80 character limit per line
set colorcolumn=81

" Highlight search results and incremental search results
set incsearch
set hlsearch

" Make backspace behave in an expected way - delete line when backspacing
" beginning of line
set backspace=indent,eol,start

" Turn off mouse interactions
set mouse=

" Set up vim-slime for use within tmux
let g:slime_target="tmux"
